# version: "3.8"

services:
  nginx-compose:
    container_name: nginx-compose
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./data-nginx:/etc/nginx/conf.d"
      - "./src-nginx:/usr/share/nginx/html"
  mongo-compose:
    container_name: mongo-compose
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dimas
      MONGO_INITDB_ROOT_PASSWORD: dimas
      MONGO_INITDB_ROOT_DATABASE: dimas
    volumes:
      - "./data-mongo:/data/db"
  mysql-compose:
    container_name: mysql-compose
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password 
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      # MYSQL_USER: dimas
      # MYSQL_PASSWORD: dimas
      MYSQL_ROOT_PASSWORD: dimas
      # MYSQL_DATABASE: dimas
    volumes:
      - "./data-mysql:/var/lib/mysql"
     